/* Populate tabla clientes */
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesor1@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe1@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.1torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.1lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma1@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hel1m@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johns1on@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissi1des@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gos1ling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.l1ee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornad1o.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profe1so2r@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profes1o2r@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe21@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.12torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus12.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma2@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.he2lm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.john2son@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlis2sides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.g2osling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.l2ee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornad2o.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profe3s3or@bolsadeideas.com', '2018-01-01','soltero');