/* Populate tabla clientes */
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesour@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.dofe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusf.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmufss.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamasdma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.healm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johdnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlisssides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jamesdf.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magmaa.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tordanado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'proawfesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profwesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.edoe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linrrus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmrqus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gaqmma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.qhelm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.jjohnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vljissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jameskj.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lege@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadfdo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesdsor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesosr@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.dose@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusd.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmufs.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamfma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.haselm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johanson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlisxsides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gxosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.leex@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadxo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profxesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profebsor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.dobe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusb.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmusn.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gammna@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.henlm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissmides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gomsling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.leme@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadom.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profeskor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesokr@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doke@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusk.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.llerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamlma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hellm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnoson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissoides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.goosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.leoe@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadoo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesior@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesour@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doue@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusu.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmusu.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.igamma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richarid.helm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.pjohnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vplissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jameps.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lpee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadpo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profeysor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesyor1@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doey1@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.y1torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.y1lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gammay1@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hely1m@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnys1on@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissyi1des@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.go.s1ling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.l.1ee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornad.1o.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profe.1so2r@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profes.1o2r@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doe.21@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linus.1.2torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus1.2.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamma.2@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.he2vvlm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnv2son@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlis2vsides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.g2vosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lv2ee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadv2o.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profec3s3or@bolsadeideas.com', '2018-01-01','soltero');