/* Populate tabla clientes */
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profeasour@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.doafe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusfq.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmufsqs.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamasadma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hesalm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johdfdnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissgsides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jamesdfh.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magmaja.lee@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tordhanado.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'prohawfesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profhwesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.ejdoe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linrrhus.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmrkqus.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gaqkmma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hqhelm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.jjgohnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vljfissides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jameskfj.gosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'mafgma.lege@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadfdo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'fprofesdsor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'pfrofesosr@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'johfn.dose@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'lihnusd.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasdmufs.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gsamfma@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richards.haselm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.jdohanson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlgisxsides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jamesy.gxosling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magmar.leex@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'torneadxo.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'proufxesor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profuebsor@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.diobe@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusub.torvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmuson.lerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamomna@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.hlenlm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.jolhnnson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlkissmides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'jamesk.gomsling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.lemte@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadomt.roe@gmail.com', '2018-03-05','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profeskror@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Andrés', 'Guzmán', 'profesoker@bolsadeideas.com', '2018-01-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Mr. John', 'Doe', 'john.dokee@gmail.com', '2018-01-02','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Linus', 'Torvalds', 'linusk.teorvalds@gmail.com', '2018-01-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Rasmus', 'Lerdorf', 'rasmus.lleerdorf@gmail.com', '2018-01-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Erich', 'Gamma', 'erich.gamlmwa@gmail.com', '2018-02-01','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Richard', 'Helm', 'richard.helwlm@gmail.com', '2018-02-10','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Ralph', 'Johnson', 'ralph.johnowson@gmail.com', '2018-02-18','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','John', 'Vlissides', 'john.vlissowides@gmail.com', '2018-02-28','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Dr. James', 'Gosling', 'james.gooisling@gmail.com', '2018-03-03','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Magma', 'Lee', 'magma.leioe@gmail.com', '2018-03-04','soltero');
INSERT INTO clientes (tipoid, nombre, apellido, email, create_at, estado) VALUES('cc','Tornado', 'Roe', 'tornadoio.roe@gmail.com', '2018-03-05','soltero');
